### ISSUE TITLE
How to use this font?

### ISSUE THREAD

**Issue by real-ashwin** [christiannaths/Climacons-Font#6]
How to map the forecast.io icons to the css classes?

Forecast returns clear-night, partly-cloudy-night etc. Is it possible to map those values to your CSS classes?

Thanks.

**Comment by christiannaths** [comment]
Yup! You'd just need to update the stylesheet for your project (https://github.com/christiannaths/Climacons-Font/blob/master/webfont/climacons-font.css). You'll want to add class names in addition to the existing ones probably, so (as an example) something like this:

``` css
.climacon.cloud.moon:before {
    content: "\e002";
}
```

would become this:

``` css
.climacon.partly-cloudy-night:before,
.climacon.cloud.moon:before {
    content: "\e002";
}
```

You'd need to do this for every forcast.io mapping you plan on using. Your html would then need to look like this:

``` html
<span class="climacon <forcast-io-class-name-here>"></span>
```

How you dynamically add the forcast.io class name is up to you.
